version: '2'
services:
  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      default: {}
      monitoring: {}

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.0
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"

networks:
   monitoring:
      external: true
